languageCode = "de-de"
title = "ArtCommissions-SabrinaFrank -Portfoliowebsite-"
baseurl = "https://www.ArtCommissions-SabrinaFrank.de/"
theme = ""

[params]
  name = "Sabrina Frank"
  description = "Künstlerin & Studentin"
  copyright = "Creative Commons Licence - Hugo Theme: Prologue - Edited by: Sabrina Frank"


[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/ArtCommissionsSabrinaFrank/?ref=py_c"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/SabiFrank"


[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "mailto:sabrina.frank.95@gmail.com"

# Portfolio column one

[[params.portfolio1]]
  title = "Titel"
  alt = ""
  source = "img/pic02.jpg"
  url = "#"

[[params.portfolio1]]
  title = "Titel"
  alt = ""
  source = "img/pic03.jpg"
  url = "#"

# Portfolio column two

[[params.portfolio2]]
  title = "Titel"
  alt = ""
  source = "img/pic04.jpg"
  url = "#"

[[params.portfolio2]]
  title = "Titel"
  alt = ""
  source = "img/pic05.jpg"
  url = "#"

# Portfolio column 3

[[params.portfolio3]]
  title = "Titel"
  alt = ""
  source = "img/pic06.jpg"
  url = "#"

[[params.portfolio3]]
  title = "Titel"
  alt = ""
  source = "img/pic07.jpg"
  url = "#"
